# begin-snippet: TemplateExpression-parameters
parameters:
  - name: Environments
    type: object
    default:
      - name: Dev
        displayName: "Development"
      - name: Test
        displayName: "Testing"
      - name: Prod
        displayName: "Production"
  # end-snippet
  - name: DependsOn
    type: string
    default: "Build"

trigger:
  - main

pool:
  vmImage: ubuntu-latest

# begin-snippet: TemplateExpression-variables1
variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    Environment: "Production"
  ${{ else }}:
    Environment: "Not-Production"
# end-snippet

stages:
  - stage: Build
    jobs:
      - job: Version
        displayName: "Version Job"
        steps:
          - script: echo "Setting version based on branch."
            displayName: "Set Version"

      - job: Build

        # begin-snippet: TemplateExpression-conditional-dependson
        ${{ if ne(parameters.DependsOn, '') }}:
          dependsOn:
            - Version
        # end-snippet

        steps:
          - script: echo Building...
            displayName: "Build Job"

          - script: echo "Build completed successfully."

          - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
              - publish: $(Build.ArtifactStagingDirectory)
                artifact: drop
                displayName: "Publish Artifact"

      - job: Notify
        displayName: "Notify Build Completion"
        # begin-snippet: TemplateExpression-conditional-dependson-extra
        dependsOn:
          - Version
          - ${{ if ne(parameters.DependsOn, '') }}:
              - ${{ parameters.DependsOn }}
        # end-snippet

        steps:
          - script: echo "Build completed. Notifying team."
            displayName: "Notify Team"

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      # begin-snippet: TemplateExpression-conditional-each
      - ${{ each env in parameters.Environments }}:
          - stage: DeployTo${{ env.name }}
            jobs:
              - job: DeployTo${{ env.name }}
                displayName: "Deploy to ${{ env.name }}"
                steps:
                  - script: echo "Deploying to ${{ env.name }} environment..."
                    displayName: "Deploy to ${{ env.name }}"
                  # end-snippet

                  # begin-snippet: TemplateExpression-conditional-step
                  - ${{ if eq(env.name, 'Prod') }}:
                      - script: echo "Running production specific tasks."
                        displayName: "Production Tasks"
                  # end-snippet

                  - script: echo "Deployment to ${{ env.name }} completed."
                    displayName: "Deployment Complete"
              - ${{ if eq(env.name, 'Prod') }}:
                  - job: NotifyProd
                    displayName: "Notify Production Deployment"
                    steps:
                      - script: echo "Notifying team about production deployment."
                        displayName: "Notify Team"
