parameters:
  - name: Environments
    type: object
    default:
      - name: Dev
        displayName: "Development"
      - name: Test
        displayName: "Testing"
      - name: Prod
        displayName: "Production"

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
    Environment: "Production"
  ${{ else }}:
    Environment: "Not-Production"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - script: echo Building...
            displayName: "Build Job"

          - script: echo "Build completed successfully."

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main') }}:
      - ${{ each env in parameters.Environments }}:
          - stage: DeployTo${{ env.name }}
            jobs:
              - job: DeployTo${{ env.name }}
                displayName: "Deploy to ${{ env.name }}"
                steps:
                  - script: echo "Deploying to ${{ env.name }} environment..."
                    displayName: "Deploy to ${{ env.name }}"

              - ${{ if eq(env.name, 'Prod') }}:
                  - job: NotifyProd
                    displayName: "Notify Production Deployment"
                    steps:
                      - script: echo "Notifying team about production deployment."
                        displayName: "Notify Team"
